Update Analyze.yml

diff --git a/.github/workflows/Analyze.yml b/.github/workflows/Analyze.yml
--- a/.github/workflows/Analyze.yml
+++ b/.github/workflows/Analyze.yml
@@ -56,7 +56,16 @@ jobs:
 
     - name: Switch device type
       run: |
-        python main.py -t 0 ${{ github.event.inputs.device }}
+        if [ "${{ github.event.inputs.device }}" = "Phone" ]; then
+            python main.py -t 0 ph
+          elif [ "${{ github.event.inputs.device }}" = "Pad" ]; then
+            python main.py -t 0 p
+          elif [ "${{ github.event.inputs.device }}" = "Fold" ]; then
+            python main.py -t 0 f
+          else
+            echo "Invalid device specified."
+            exit 1
+          fi
 
     - name: Unzip payload.bin
       run: |
