update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,18 +1,48 @@
-name: Test
+name: Analyze & Push
 
 on:
   workflow_dispatch:
+    inputs:
+      device:
+        description: "设备类型"
+        required: true
+        type: choice
+        options:
+        - Phone
+        - Pad
+        - Fold
+      link:
+        description: 'ROM 链接'
+        required: true
+      devicename:
+        description: '设备名'
+        required: false
+      osversion:
+        description: '系统版本'
+        required: false
 
 jobs:
   Analyze:
-    runs-on: ubuntu-latest
+    runs-on: windows-latest
 
     steps:
+    - name: Maximizing storage
+      uses: easimon/maximize-build-space@master
+      with:
+        swap-size-mb: 8192
+        root-reserve-mb: 4096
+        temp-reserve-mb: 4096
+        remove-dotnet: 'true'
+        remove-android: 'true'
+        remove-haskell: 'true'
+
     - name: Checkout code
       uses: actions/checkout@v4
-
+    
     - name: Install dependence
       run: |
+        wget https://dl.androidaapt.com/aapt-windows.zip
+        7z o aapt-windows.zip
         pip install -r requirements.txt
 
     - name: Download extract.erofs
@@ -23,7 +53,7 @@ jobs:
         extract: true
         fileName: 'erofs-utils-*-Linux_x86_64-*.zip'
 
-    - name: Download extract.erofs
+    - name: Download payload-dumper-go
       uses: robinraju/release-downloader@v1.10
       with:
         repository: "ssut/payload-dumper-go"
@@ -31,6 +61,100 @@ jobs:
         extract: true
         fileName: 'payload-dumper-go_*_linux_amd64.tar.gz'
 
-    - name: Install dependence
+    - name: Remove files
       run: |
-        ls
+       rm *.tar.gz *.zip
+
+    - name: Download ROM
+      run: |
+        python main.py -d ${{ github.event.inputs.link }}
+
+    - name: Switch device type
+      run: |
+        if [ "${{ github.event.inputs.device }}" = "Phone" ]; then
+            python main.py -t 0 ph
+          elif [ "${{ github.event.inputs.device }}" = "Pad" ]; then
+            python main.py -t 0 p
+          elif [ "${{ github.event.inputs.device }}" = "Fold" ]; then
+            python main.py -t 0 f
+          else
+            echo "Invalid device specified."
+            exit 1
+          fi
+
+    - name: Unzip payload.bin
+      run: |
+        python main.py -p
+        rm *.zip
+
+    - name: Unzip img
+      run: |
+        python main.py -i
+        rm payload.bin
+    
+    - name: Unzip files
+      run: |
+        ./extract.erofs -i product.img -x -T8
+        rm *.img
+    
+
+    - name: Remove exclude apks
+      run: |
+        python main.py -a
+
+    - name: Upload Special apks
+      uses: actions/upload-artifact@v4
+      with:
+        name: Special_apks
+        path: |
+          output_apk/MIUIScreenRecorder.apk
+          output_apk/MIUIScreenRecorderLite.apk
+          output_apk/MIUISecurityCenter.apk
+          output_apk/MiuiHome.apk
+          output_apk/AiAsstVision.apk
+          
+    - name: Get version
+      run: |
+        python main.py -n
+
+    - name: Update database
+      run: |
+        python main.py -u
+
+    - name: Rename
+      run: |
+        python main.py -m
+
+    - name: Upload app_version.json and app_code.json
+      uses: actions/upload-artifact@v4
+      with:
+        name: Update_json
+        path: |
+          app_version.json
+          app_code.json
+    
+    - name: Upload update_apks
+      uses: actions/upload-artifact@v4
+      with:
+        name: Update_apks
+        path: |
+          update_apk
+          update_name_apk
+
+    - name: Update
+      run: |
+        python main.py -t 1 ph
+            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
+            git config --global user.name "${GITHUB_ACTOR}"
+        if [ "${{ github.event.inputs.device }}" = "Phone" ]; then
+            git add phone/
+          elif [ "${{ github.event.inputs.device }}" = "Pad" ]; then
+            git add pad/
+          elif [ "${{ github.event.inputs.device }}" = "Fold" ]; then
+            git add fold/
+          else
+            echo "Invalid device specified."
+            exit 1
+          fi
+        git commit -m "Update Database ${{ github.event.inputs.devicename }} ${{ github.event.inputs.osversion }}"
+        git push origin main
